export enum CustomComponentEnum {
    imgSingle = 'imgSingle',
    service = 'service',
    imgSlide = 'imgSlide',
    notice = 'notice',
    coupon = 'coupon',
    pinTuan = 'pinTuan',
    search = 'search',
    navBar = 'navBar',
    goodTabBar = 'goodTabBar',
    article = 'article',
    articleClassify = 'articleClassify',
    video = 'video',
    goods = 'goods',
    record = 'record',
    blank = 'blank',
    textarea = 'textarea',
    imgWindow = 'imgWindow',
    content = 'content',
    groupPurchase = 'groupPurchase',
    seckill = 'seckill',
    adpop = 'adpop'
}
