import {
    Button,
    Calendar,
    Field,
    Popup,
    Cascader,
    CountDown,
    BackTop,
    NoticeBar,
    ShareSheet,
    Uploader,
    Notify,
    Tag,
    Toast,
    Dialog,
    PullRefresh,
    SwipeCell,
    Stepper,
    CheckboxGroup,
    Checkbox,
    Image,
    Step,
    Steps,
    Divider,
    Icon,
    Empty,
    Tabs,
    Tab,
    Loading,
    Badge,
    CellGroup,
    Radio,
    RadioGroup,
    Picker,
    Progress,
    Sidebar,
    SidebarItem,
    DropdownMenu,
    DropdownItem,
    Search
} from 'vant';
import 'vant/lib/index.css';

export default defineNuxtPlugin(({ vueApp }) => {
    vueApp
        .use(Button)
        .use(Calendar)
        .use(Field)
        .use(Popup)
        .use(Cascader)
        .use(CountDown)
        .use(BackTop)
        .use(NoticeBar)
        .use(ShareSheet)
        .use(Uploader)
        .use(Notify)
        .use(Tag)
        .use(Toast)
        .use(Dialog)
        .use(PullRefresh)
        .use(SwipeCell)
        .use(Stepper)
        .use(CheckboxGroup)
        .use(Checkbox)
        .use(Image)
        .use(Step)
        .use(Steps)
        .use(Divider)
        .use(Icon)
        .use(Empty)
        .use(Tab)
        .use(Tabs)
        .use(Loading)
        .use(Badge)
        .use(CellGroup)
        .use(RadioGroup)
        .use(Radio)
        .use(Picker)
        .use(Progress)
        .use(Sidebar)
        .use(SidebarItem)
        .use(DropdownMenu)
        .use(DropdownItem)
        .use(Search)
        ;
})