version: "3"
services:
  nuxt:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile      
    container_name: nuxt-pc-app
    ports:
      - 4000:4000
  nginx:
    restart: always
    image: nginx 
    container_name: nginx
    ports:
      - 4000:80
    volumes:
      - /root/nuxt/nginx/default.conf:/etc/nginx/conf.d/default.conf
        
